# Generated by Django 2.1 on 2017-12-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinfo',
            name='course_teacher',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='courseinfo',
            name='course_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='course_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
