# Generated by Django 2.0 on 2017-12-30 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_courseinfo_course_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinfo',
            name='course_pos',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
