# Generated by Django 2.0 on 2017-12-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_courseinfo_course_pos'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
