# Generated by Django 2.0 on 2018-01-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_userinfo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hwgrade',
            name='grade_submit',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
