# Generated by Django 2.0 on 2018-01-05 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_hwgrade_grade_submit'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='source_type',
            field=models.IntegerField(null=True),
        ),
    ]
