# Generated by Django 2.0 on 2018-01-05 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_source_source_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='HwSubmit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_status', models.IntegerField(null=True)),
                ('submit_homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Homework')),
                ('submit_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.UserInfo')),
            ],
        ),
    ]
