# Generated by Django 2.0 on 2018-01-05 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0009_hwsubmit'),
    ]

    operations = [
        migrations.AddField(
            model_name='hwsubmit',
            name='submit_time',
            field=models.DateTimeField(null=True),
        ),
    ]
