# Generated by Django 2.0.2 on 2018-03-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0010_hwsubmit_submit_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinfo',
            name='course_exam',
            field=models.DateTimeField(null=True),
        ),
    ]
