# Generated by Django 2.0.2 on 2018-03-06 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0012_auto_20180305_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liuyan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=400, null=True)),
                ('name', models.CharField(max_length=10)),
                ('role', models.CharField(max_length=10)),
                ('datetime', models.DateTimeField()),
            ],
        ),
    ]
