# Generated by Django 2.0.2 on 2018-03-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0013_liuyan'),
    ]

    operations = [
        migrations.AddField(
            model_name='liuyan',
            name='item_id',
            field=models.IntegerField(null=True),
        ),
    ]
