# Generated by Django 2.0.2 on 2018-03-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0014_liuyan_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liuyan',
            name='role',
            field=models.IntegerField(),
        ),
    ]
